# TWITTER API CREDENTIALS
BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAMMBWgEAAAAAzvoGSyVW2eN1NUEmzMZO2MHQHSM%3Ddv6uIhNZjD1Td9QSX3DVwzSUO4WdEaM5XU6IpHiEkYpmJ49N6E"  # Your Twitter Bearer Token Credential string

